name: stakkeo
version: '0.1.0.0'
description: Please see the README on GitHub at <https://github.com/sigrlami/stakkeo#readme>
author: Sergey Bushnyak
maintainer: sergey.bushnyak@sigrlami.eu
copyright: ! 'Copyright: (c) 2018 Sergey Bushnyak'
license: Apache
github: sigrlami/stakkeo
extra-source-files:
- ChangeLog.md
- README.md
ghc-options:
- -threaded
- -rtsopts
- -with-rtsopts=-N
dependencies:
- base >=4.7 && <5
- gi-gtk
- haskell-gi-base
executables:
  stakkeo-album:
    main: Main.hs
    source-dirs: src
